name: CI PR
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.1.4
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Set BST for tests
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/London"

      - name: Run typescript build
        run: pnpm build

      - name: Run tests
        run: pnpm test:ci

      - name: Run lints
        run: pnpm lint

      - name: Deploy to Vercel for Preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          git remote add vercel https://vercel:${{ secrets.VERCEL_TOKEN }}@github.com/${{ github.repository }}
          git fetch vercel main
          git push vercel HEAD:refs/heads/main
